### ISSUE TITLE
breaks with im channel being added to channel_types

### ISSUE THREAD

**Issue by pranavksentieo** [MeltanoLabs/tap-slack#24]
Following scopes works with ["public_channel", "private_channel", "mpim"] channel_types but starts to break when "im" is added, and the error message looks too generic to debug.

scopes: `channels:history channels:read groups:history groups:read im:history im:read mpim:history mpim:read users:read users:read.email` 
config
```
      - name: tap-slack
        select:
        - messages.*
        config:
          channel_types: ["public_channel", "private_channel", "mpim", "im"]
```
![image](https://github.com/MeltanoLabs/tap-slack/assets/95340258/7bbd33a6-4248-4af2-a15b-0be306737ba2)
